# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=256, verbose_name='タスク')),
                ('contents', models.TextField(blank=True, verbose_name='詳細')),
                ('priority', models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], verbose_name='優先度')),
                ('is_done', models.BooleanField(verbose_name='完了')),
                ('limmit_date', models.DateField(null=True, verbose_name='期限日')),
                ('limmit_time', models.TimeField(null=True, verbose_name='期限時間')),
                ('create_datetime', models.DateTimeField(auto_now=True, verbose_name='作成日')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, verbose_name='更新日')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TodoUser', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
    ]
