# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='limmit_time',
            field=models.TimeField(blank=True, null=True, verbose_name='期限時間'),
        ),
    ]
